apiVersion: v1
kind: Pod
metadata:
  name: app-kuber-with-gpu
  labels:
    environment: dev
    app: http-server
spec:
  nodeSelector:
    gpu: "true"
  containers:
    - name: app-kuber-container
      image: dannycrief/kuber:0.1
      ports:
        - containerPort: 8000
