apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuber-rs-1
  labels:
    app: kuber-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - name: kube-app
          image: dannycrief/kuber