apiVersion: v1
kind: Service
metadata:
  name: endpoints-service
spec:
  ports:
    - port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: endpoints-service
subsets:
  - addresses:
      - ip: 10.244.0.89
      - ip: 10.244.0.94
  - ports:
      - port: 8000